import fs from 'node:fs';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)).replace(/\/$/,'');
const ids = new Map(); let selected=false; let downloaded=[];
// Deterministic timers exercise notification expiry/reset without sleeping or claiming browser QA.
let clock=0,nextTimer=0;const timers=new Map();
globalThis.setTimeout=(fn,delay=0)=>{const id=++nextTimer;timers.set(id,{at:clock+delay,fn});return id;};
globalThis.clearTimeout=id=>timers.delete(id);
function advance(ms){clock+=ms;for(const [id,timer] of [...timers])if(timer.at<=clock){timers.delete(id);timer.fn();}}

class E {
 constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners={};this.value='';this.checked=false;this.disabled=false;this.hidden=false;this.textContent='';this.style={setProperty(k,v){this[k]=v}};this.classSet=new Set();this.classList={toggle:(k,on)=>{if(on??!this.classSet.has(k))this.classSet.add(k);else this.classSet.delete(k)},contains:k=>this.classSet.has(k)};this.parentElement={classList:{toggle(){}}};}
 set id(x){this._id=x;ids.set(x,this)}get id(){return this._id}
 append(...children){for(const c of children)if(c&&typeof c==='object')c.parentElement=this;this.children.push(...children)} contains(node){return node===this||this.children.some(c=>c&&typeof c.contains==='function'&&c.contains(node))} prepend(...children){for(const c of children)if(c&&typeof c==='object')c.parentElement=this;this.children.unshift(...children)} replaceChildren(...children){this.children=[];this.append(...children)}
 setAttribute(k,v){this[k]=v} getAttribute(k){return this[k]??null} removeAttribute(k){delete this[k]} addEventListener(k,f){(this.listeners[k]??=[]).push(f)}
 async dispatch(k,detail={}){for(const f of this.listeners[k]??[])await f({target:this,preventDefault(){},stopPropagation(){},...detail})}
 async click(){if(this.tagName==='a')downloaded.push(this);else await this.dispatch('click')}remove(){}focus(){document.activeElement=this}select(){selected=true}scrollIntoView(){}showModal(){this.open=true}close(){this.open=false}setPointerCapture(id){this.pointerCapture=id}hasPointerCapture(id){return this.pointerCapture===id}releasePointerCapture(){this.pointerCapture=null}getBoundingClientRect(){return {top:0,height:800,width:600}}
 checkValidity(){const n=Number(this.value);return Number.isFinite(n)&&n>=Number(this.min??-Infinity)&&n<=Number(this.max??Infinity)&&(!this.step||Math.abs(n/Number(this.step)-Math.round(n/Number(this.step)))<1e-7)}
}
let html=fs.readFileSync(root+'/web/index.html','utf8');
for(let m of html.matchAll(/<([a-z][a-z0-9]*)\b([^>]*\bid="([^"]+)"[^>]*)>/g)){let e=new E(m[1]);e.id=m[3];for(let a of m[2].matchAll(/([\w-]+)="([^"]*)"/g)) e[a[1]]=a[2];e.hidden=/\bhidden\b/.test(m[2])}
globalThis.document={getElementById:id=>ids.get(id),createElement:t=>new E(t),body:new E('body'),documentElement:new E('html'),querySelectorAll:selector=>selector==='[data-icon]'?[...ids.values()].filter(e=>e['data-icon']):[],execCommand:()=>false};
Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});Object.defineProperty(globalThis,'crypto',{value:webcrypto,configurable:true});const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
if(process.env.QA_BUNDLE || process.argv.includes('--bundle')){let bundle=fs.readFileSync(root+'/dist/visage-workbench.html','utf8').match(/<script>([\s\S]*)<\/script>/)[1];(await import('node:vm')).runInThisContext(bundle);}else await import(root+'/web/app.mjs');const $=id=>ids.get(id);const event=async(id,v,k='change')=>{$(id).value=String(v);await $(id).dispatch(k)};const toggle=async(id,v)=>{$(id).checked=v;await $(id).dispatch('change')};
const prompt=()=>$('prompt-output').value;const initial=prompt();assert.equal($('status').hidden,true,'initialization must not silently fail: '+$('status').textContent);assert(initial.length>100);console.log('PASS initialize prompt',initial.length);
assert.equal($('reference-image').hidden,true);assert.equal($('reference-image').getAttribute('src'),null);assert.equal($('reference-empty').hidden,false);assert.equal($('reference-source').hidden,true);assert.equal($('clear-reference').hidden,true);assert.equal($('load-example').hidden,true);assert.equal($('load-example').disabled,true);console.log('PASS image-free initial preview is empty with no image src');
await toggle('body-enabled',true);assert.equal($('capture').value,'full_body');assert.equal($('body-fields').hidden,false);let axis=[...ids.keys()].find(k=>k.startsWith('body-')&&k.endsWith('-range'));let stem=axis.slice(0,-6);assert($(axis).disabled);await toggle(stem+'-enabled',true);assert(!$(axis).disabled);await event(axis,95,'input');assert.equal($(stem+'-number').value,'95');assert(prompt()!==initial);console.log('PASS body enable and slider value/description',stem,$(stem+'-description').textContent);
let bodyPrompt=prompt();await event('capture','head');assert(prompt()!==bodyPrompt);await event('capture','full_body');assert.equal(prompt(),bodyPrompt);console.log('PASS head/full-body roundtrip');
for(let id of ['hair-select','makeup-select']){let opts=$(id).children.flatMap(c=>c.tagName==='optgroup'?c.children:[c]);let chosen=opts.find(x=>!['inherit','off'].includes(x.value));await event(id,chosen.value);assert.equal($(id).value,chosen.value);console.log('PASS select',id,chosen.value)}
await event('age-mode','selected');await event('age-number',47);assert(prompt().includes('47'));let ageP=prompt();await event('age-number',17);assert.equal(prompt(),ageP);await event('expression-select','slight_smile');console.log('PASS age validation and expression');
await $('save-local').click();const saved=prompt();await $('randomize').click();assert(prompt()!==saved);const random=prompt();const seed=$('seed-value').textContent;await $('save-local').click();await $('reset').click();assert.equal(prompt(),initial);await $('load-local').click();assert.equal(prompt(),random);assert.equal($('seed-value').textContent,seed);console.log('PASS random, reset, save/load exact prompt+seed');
await $('copy-prompt').click();assert(selected);assert($('status').textContent.includes('Ctrl+C'));console.log('PASS copy fallback selection');
const stable=prompt();$('import-file').files=[{name:'bad.json',size:1,text:async()=>'{'}];await $('import-file').dispatch('change');assert.equal(prompt(),stable);assert($('status').textContent.includes('导入失败'));console.log('PASS invalid JSON preserving state');
let text=storage.values().next().value;await $('export-json').click();assert(downloaded.length===1);await $('reset').click();$('import-file').files=[{name:'good.json',size:text.length,text:async()=>text}];await $('import-file').dispatch('change');assert.equal(prompt(),stable);console.log('PASS export click/import roundtrip');
let release;$('import-file').files=[{name:'slow.json',size:text.length,text:()=>new Promise(r=>{release=r})}];let pending=$('import-file').dispatch('change');await $('reset').click();assert.equal(prompt(),initial);release(text);await pending;console.log('ASYNC IMPORT AFTER RESET',prompt()===initial?'PASS newer state retained':'FAIL delayed import overwrites newer reset');
console.log('No real browser render, layout, native file chooser, browser storage or clipboard API was exercised. This is a minimal DOM event harness only.');

await toggle('body-enabled',true);await toggle(stem+'-enabled',true);await event(axis,81,'input');const remembered=prompt();await toggle('body-enabled',false);assert($(axis).disabled);await toggle('body-enabled',true);assert.equal($(stem+'-number').value,'81');assert.equal(prompt(),remembered);console.log('PASS body off/on retains values');
let keep=prompt();await event('hair-search','zzzzzzzz','input');assert.equal(prompt(),keep);await event('makeup-search','zzzzzzzz','input');assert.equal(prompt(),keep);console.log('PASS filtered catalog preserves selection/prompt');
for(let i=0;i<100;i++)await event(axis,i,'input');assert.equal($(stem+'-number').value,'99');assert($(stem+'-description').textContent.includes('高区间'));console.log('PASS 100 repeated edits sync value + description');
keep=prompt();for(let f of [{name:'wrong.json',size:2,text:async()=>'{}'},{name:'large.json',size:2000000,text:async()=>text}]){$('import-file').files=[f];await $('import-file').dispatch('change');assert.equal(prompt(),keep)}console.log('PASS invalid schema / oversized import preserves state');
let release2;$('import-file').files=[{name:'slow.json',size:text.length,text:()=>new Promise(r=>release2=r)}];pending=$('import-file').dispatch('change');$('import-file').files=[];await $('import-file').dispatch('change');release2(text);await pending;assert.equal(prompt(),keep);console.log('PASS canceled later import invalidates delayed old import');

await $('reset').click();
await event('subject-appearance','东亚外貌 / 自定义原文');await event('subject-gender','androgynous adult');await event('subject-skin','warm medium brown');await event('subject-shape','heart-shaped');
const customIdentity=prompt();await $('randomize').click();assert.equal($('subject-appearance').value,'东亚外貌 / 自定义原文');assert.equal($('subject-gender').value,'androgynous adult');assert.equal($('subject-skin').value,'warm medium brown');assert.equal($('subject-shape').value,'heart-shaped');assert(!$('undo-randomize').disabled);await $('undo-randomize').click();assert.equal(prompt(),customIdentity);assert($('undo-randomize').disabled);console.log('PASS exact subject text, constrained reroll and atomic undo');
const noseStem='head-nose-bridge_width';await toggle(noseStem+'-enabled',true);await event(noseStem+'-number',50);await $(noseStem+'-lock').click();const fixedPrompt=prompt();assert.equal($(noseStem+'-lock')['aria-pressed'],'true');await $('randomize').click();assert.equal($(noseStem+'-number').value,'50');assert($('status').textContent.includes('关联组'));await event(noseStem+'-number',55);assert($('undo-randomize').disabled);await $('randomize').click();assert.equal($(noseStem+'-number').value,'55');console.log('PASS fixed neutral, manual edit updates fixed value, correlation skip and undo invalidation');
await event(noseStem+'-min',60);await event(noseStem+'-max',64);await $(noseStem+'-cancel-range').click();assert.equal($(noseStem+'-min').value,'0');await event(noseStem+'-min',60);await event(noseStem+'-max',64);await $(noseStem+'-apply-range').click();const conflictPrompt=prompt(),conflictSeed=$('seed-value').textContent;await $('randomize').click();assert.equal(prompt(),conflictPrompt);assert.equal($('seed-value').textContent,conflictSeed);assert($('status').textContent.includes('固定值不在范围内'));await $(noseStem+'-clear-range').click();console.log('PASS range cancel, explicit conflict atomicity and clearing');
const noseGroup=$('lock-group-head-groups-4');assert(noseGroup);await noseGroup.click();assert.equal(noseGroup['aria-pressed'],'true');await $(noseStem+'-lock').click();assert.equal(noseGroup['aria-pressed'],'mixed');console.log('PASS mixed region lock and per-field unlock');
await event('hair-select','blunt_bob');await $('hair-add-choice').click();await event('hair-select','off');await $('hair-add-choice').click();await $('appearance-hair-lock').click();await $('randomize').click();assert.equal($('hair-select').value,'off');await $('appearance-hair-lock').click();await $('randomize').click();assert(['off','blunt_bob'].includes($('hair-select').value));await $('save-local').click();const constrainedSaved=prompt();await $('reset').click();await $('load-local').click();assert.equal(prompt(),constrainedSaved);console.log('PASS appearance candidate pool, off lock and persisted constraints');
const old=JSON.parse(storage.values().next().value);delete old.constraints;delete old.sampling;old.version='workbench-v0.1';$('import-file').files=[{name:'legacy.json',size:5000,text:async()=>JSON.stringify(old)}];await $('import-file').dispatch('change');assert.equal(prompt(),constrainedSaved);assert.equal($('subject-appearance-lock')['aria-pressed'],'false');console.log('PASS v0.1 migration preserves values and begins unlocked');
await $('randomize').click();await $('reset').click();assert($('undo-randomize').disabled);assert.equal(prompt(),initial);console.log('PASS reset clears live constraints and undo; saved configuration retained');
await $('lock-everything').click();const fullyLocked=prompt(),fullyLockedSeed=$('seed-value').textContent;await $('randomize').click();assert.equal(prompt(),fullyLocked);assert.equal($('seed-value').textContent,fullyLockedSeed);assert($('status').textContent.includes('没有可变化'));await $('unlock-everything').click();assert.equal(prompt(),fullyLocked);console.log('PASS all-lock no-op preserves seed and unlock preserves values');
await toggle('body-enabled',true);await toggle(stem+'-enabled',true);await event(axis,81,'input');await $('randomize-tab').click();assert.equal($(stem+'-number').value,'81');await event(stem+'-min',20);await event(stem+'-max',30);await $(stem+'-apply-range').click();await $('randomize').click();assert(Number($(stem+'-number').value)>=20&&Number($(stem+'-number').value)<=30);console.log('PASS head tab preserves body; global reroll includes bounded enabled body');
const legacyFace={version:'workbench-v0.1',profile:{schema_version:'face-v0.1',subject:{age_group:'adult',gender_presentation:'person'}},appearance:{version:'appearance-v0.1'},body:{version:'body-v0.1',state:'off',controls:{}},capture:'head',seed:'legacy-face',archetypes:['beautiful','elegant'],headEnabled:true};
$('import-file').files=[{name:'legacy-face.json',size:500,text:async()=>JSON.stringify(legacyFace)}];await $('import-file').dispatch('change');await event('subject-appearance','exact legacy upgrade');assert.equal($('subject-appearance').value,'exact legacy upgrade');await toggle('head-soft_tissue-upper_medial_cheek_fullness-enabled',true);assert(!$('head-soft_tissue-upper_medial_cheek_fullness-number').disabled);await $('save-local').click();const upgraded=JSON.parse(storage.values().next().value);assert.equal(upgraded.profile.schema_version,'face-v0.2');assert.equal(legacyFace.profile.schema_version,'face-v0.1');console.log('PASS explicit v0.2 control edit upgrades legacy face profile without changing source');
await $('randomize').click();await event('head-eyes-eye_size-number',77);assert($('seed-value').textContent.includes('配置已编辑'));await $('save-local').click();assert.equal(JSON.parse(storage.values().next().value).sampling.status,'historical');console.log('PASS edited-since-sampling UI marker and honest exported provenance');

// v0.11 shell interaction coverage (DOM events only, never browser/render evidence).
await $('reset').click();const originalCharacterPrompt=prompt();
await $('tab-appearance').click();assert.equal($('panel-head').hidden,true);assert.equal($('panel-appearance').hidden,false);assert.equal($('tab-appearance')['aria-selected'],'true');
await $('tab-appearance').dispatch('keydown',{key:'ArrowRight'});assert.equal($('panel-body').hidden,false);assert.equal(document.activeElement,$('tab-body'));await $('tab-body').dispatch('keydown',{key:'Home'});assert.equal($('panel-head').hidden,false);console.log('PASS inspector tabs, roving keyboard focus and panel visibility');
await $('theme-toggle').click();assert.equal(document.documentElement['data-theme'],'dark');assert.equal(JSON.parse(storage.get('visage.ui.v0.1')).theme,'dark');await $('theme-toggle').click();assert.equal(document.documentElement['data-theme'],'light');
await $('collapse-nav').click();assert($('app-shell').classList.contains('nav-collapsed'));assert.equal($('expand-nav').hidden,false);assert.equal(document.activeElement,$('expand-nav'));await $('expand-nav').click();assert(!$('app-shell').classList.contains('nav-collapsed'));console.log('PASS light/dark and collapsible navigation preferences');
await $('preview-divider').dispatch('keydown',{key:'Home'});assert.equal($('preview-divider')['aria-valuenow'],'35');await $('preview-divider').dispatch('keydown',{key:'ArrowUp'});assert.equal($('preview-divider')['aria-valuenow'],'35');await $('preview-divider').dispatch('keydown',{key:'End'});assert(Number($('preview-divider')['aria-valuenow'])<=78);assert(Number($('preview-divider')['aria-valuemax'])<78);
await $('preview-divider').dispatch('pointerdown',{button:0,pointerId:1});await $('preview-divider').dispatch('pointermove',{pointerId:1,clientY:432.3});await $('preview-divider').dispatch('pointerup',{pointerId:1});assert.equal($('preview-divider')['aria-valuenow'],'55');assert.equal(JSON.parse(storage.get('visage.ui.v0.1')).split,55);assert(!$('app-shell').classList.contains('is-resizing'));
await $('preview-divider').dispatch('pointerdown',{button:0,pointerId:2});await $('preview-divider').dispatch('pointercancel',{pointerId:2});assert(!$('app-shell').classList.contains('is-resizing'));console.log('PASS divider keyboard limits, drag, cancel and saved split');
await $('nav-help').click();assert.equal($('help-dialog').open,true);await $('close-help').click();assert.equal($('help-dialog').open,false);await $('nav-workspace').click();assert.equal($('workspace-files').open,true);console.log('PASS help modal and workspace navigation');
await $('rename-character').click();await event('character-name','林间');await $('rename-form').dispatch('submit');assert.equal($('current-character-title').textContent,'林间');assert.equal($('rename-form').hidden,true);
await $('rename-character').click();await event('character-name','不保存');await $('cancel-rename').click();assert.equal($('current-character-title').textContent,'林间');$('save-version').focus();await $('save-version').click();assert.equal(document.activeElement,$('save-version'));assert.equal($('current-revision').textContent,'v01');
await event('subject-shape','distinct new draft');const originalDraft=prompt();assert.notEqual(originalDraft,originalCharacterPrompt);assert.equal($('current-revision').textContent,'草稿');await $('new-character').click();assert.equal($('current-character-title').textContent,'角色 02');assert.equal($('reference-image').hidden,true);assert.equal(prompt(),originalCharacterPrompt);
await event('subject-shape','second independent character');const secondCharacterPrompt=prompt();await $('character-character-1').click();assert.equal(prompt(),originalDraft);assert.equal($('current-character-title').textContent,'林间');await $('restore-character-1-version-1').click();assert.equal(prompt(),originalCharacterPrompt);assert.equal($('current-revision').textContent,'v01');await $('character-character-2').click();assert.equal(prompt(),secondCharacterPrompt);console.log('PASS rename/cancel, independent drafts, immutable version restore and character switching');
await $('save-local').click();const workspaceSaved=storage.get('visage.workspace.v0.1');assert.equal(JSON.parse(workspaceSaved).characters.length,2);await $('new-character').click();await $('load-local').click();assert.equal($('current-character-title').textContent,'角色 02');assert.equal(prompt(),secondCharacterPrompt);assert.equal($('reference-image').hidden,true);console.log('PASS multi-character workspace save/load and non-persistence of reference images');
const beforeBadLoad=prompt();storage.set('visage.workspace.v0.1','{}');await $('load-local').click();assert.equal(prompt(),beforeBadLoad);assert($('status').textContent.includes('读取失败'));storage.set('visage.workspace.v0.1',workspaceSaved);console.log('PASS invalid workspace load preserves current state');
const emptyPrompt=prompt();await $('load-example').click();assert.equal($('reference-image').hidden,true);assert.equal($('reference-image').getAttribute('src'),null);assert.equal($('reference-empty').hidden,false);assert.equal(prompt(),emptyPrompt);
$('reference-file').files=[{name:'vector.svg',type:'image/svg+xml',size:200}];await $('reference-file').dispatch('change');assert($('status').textContent.includes('请选择 PNG'));assert.equal($('reference-image').hidden,true);
$('reference-file').files=[{name:'big.png',type:'image/png',size:11*1024*1024}];await $('reference-file').dispatch('change');assert($('status').textContent.includes('超过 10 MB'));console.log('PASS unavailable example stays empty, reference type/size validation');
const originalCreateURL=URL.createObjectURL,originalRevokeURL=URL.revokeObjectURL;const revoked=[];let nextURL=0;URL.createObjectURL=()=>`blob:test-${++nextURL}`;URL.revokeObjectURL=url=>revoked.push(url);
globalThis.Image=class{naturalWidth=500;naturalHeight=700;set src(value){queueMicrotask(()=>this.onload())}};
$('reference-file').files=[{name:'portrait.png',type:'image/png',size:200}];await $('reference-file').dispatch('change');assert.equal($('reference-image').hidden,false);assert.equal($('reference-source').textContent,'本地参考 · portrait.png');await event('subject-shape','changed after reference');assert($('reference-label').textContent.includes('参数已更改'));
const importedURL=$('reference-image').src;const importedPrompt=prompt();await $('clear-reference').click();assert(revoked.includes(importedURL));assert.equal($('reference-image').getAttribute('src'),null);assert.equal($('reference-image').hidden,true);assert.equal($('reference-empty').hidden,false);assert.equal(prompt(),importedPrompt);
let lateImage;globalThis.Image=class{naturalWidth=500;naturalHeight=700;set src(value){lateImage=this}};$('reference-file').files=[{name:'late.png',type:'image/png',size:200}];const late=$('reference-file').dispatch('change');await $('new-character').click();lateImage.onload();await late;assert.equal($('reference-image').hidden,true);assert(revoked.includes('blob:test-2'));URL.createObjectURL=originalCreateURL;URL.revokeObjectURL=originalRevokeURL;console.log('PASS decoded reference import, stale labeling, URL cleanup and async character-switch race');
console.log('UI shell event checks complete. Rendering, responsive layout, real pointer capture, native storage, chooser, image decode and clipboard still require browser QA.');

await event('subject-shape','blob: a creative label');assert.equal($('subject-shape').value,'blob: a creative label');await $('save-local').click();await $('new-character').click();await $('load-local').click();assert.equal($('subject-shape').value,'blob: a creative label');console.log('PASS exact blob-prefixed custom text remains canonical across workspace saves');

await $('save-local').click();const beforeDeep=prompt(),beforeDeepSeed=$('seed-value').textContent;const deepConfig=JSON.parse(storage.get('visage.workbench.v0.1'));deepConfig.profile.face_geometry.face_width=77;let deep={};deepConfig.profile.metadata=deep;for(let i=0;i<105;i++){deep.next={};deep=deep.next;}const deepText=JSON.stringify(deepConfig);$('import-file').files=[{name:'deep.json',size:deepText.length,text:async()=>deepText}];await $('import-file').dispatch('change');assert.equal(prompt(),beforeDeep);assert.equal($('seed-value').textContent,beforeDeepSeed);assert($('status').textContent.includes('层级过深'));assert.equal($('workspace-status').textContent,'已保存到当前浏览器');console.log('PASS workspace prevalidation keeps deeply nested rejected imports atomic');

await $('save-local').click();await $('new-character').click();assert.equal($('workspace-status').textContent,'当前会话 · 有未保存更改');console.log('PASS new character marks previously saved workspace dirty');

// v0.12: preset/custom, scoped rerolls, and copy feedback lifecycle.
await $('reset').click();const presetInitial=prompt();
await event('subject-appearance-preset','East Asian appearance');assert.equal($('subject-appearance').value,'East Asian appearance');
await event('subject-gender-preset','woman');assert.equal($('subject-gender').value,'woman');
await event('subject-skin-preset','deep brown');assert.equal($('subject-skin').value,'deep brown');
const lockBefore=$('subject-appearance-lock')['aria-pressed'];await event('subject-appearance-preset','__custom__');assert.equal(document.activeElement,$('subject-appearance'));assert.equal($('subject-appearance').value,'East Asian appearance');
await event('subject-appearance','  Exact_Custom 自定义  ');assert.equal($('subject-appearance-preset').value,'__custom__');assert.equal($('subject-appearance').value,'  Exact_Custom 自定义  ');assert.equal($('subject-appearance-lock')['aria-pressed'],lockBefore);
await event('subject-skin-preset','');assert.equal($('subject-skin').value,'');console.log('PASS subject presets, custom exact input, empty optional value and unchanged locks');
await toggle('body-enabled',true);await toggle(stem+'-enabled',true);await event(axis,81,'input');await event('hair-select','pixie');await $('hair-add-choice').click();await event('hair-select','blunt_bob');await $('hair-add-choice').click();
await $('tab-head').click();const headBody=$('body-shoulder_span-number').value,headHair=$('hair-select').value;await $('randomize-tab').click();assert.equal($('body-shoulder_span-number').value,headBody);assert.equal($('hair-select').value,headHair);assert.equal($('randomize-tab')['aria-controls'],'panel-head');
await $('tab-body').click();const bodyHead=$('head-face_geometry-face_length-number').value,bodyHair=$('hair-select').value,preBody=prompt();await $('randomize-tab').click();assert.equal($('head-face_geometry-face_length-number').value,bodyHead);assert.equal($('hair-select').value,bodyHair);assert.equal($('randomize-tab')['aria-controls'],'panel-body');await $('undo-randomize').click();assert.equal(prompt(),preBody);assert($('undo-randomize').disabled);
await $('tab-appearance').click();const appearanceHead=$('head-face_geometry-face_length-number').value,appearanceBody=$('body-shoulder_span-number').value;await $('randomize-tab').click();assert.equal($('head-face_geometry-face_length-number').value,appearanceHead);assert.equal($('body-shoulder_span-number').value,appearanceBody);console.log('PASS all three tab rerolls, no cross-tab leakage and one-step transaction undo');
let copiedText;Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{copiedText=text;}},configurable:true});
await $('copy-prompt').click();assert.equal(copiedText,prompt());assert.equal($('status').textContent,'提示词已复制。');advance(2000);assert.equal($('status').hidden,false);await $('copy-prompt').click();advance(600);assert.equal($('status').hidden,false);advance(1899);assert.equal($('status').hidden,false);advance(1);assert.equal($('status').hidden,true);console.log('PASS actual clipboard success, timed dismissal and repeated-copy timer reset');
Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw new Error('denied');}},configurable:true});document.execCommand=()=>false;await $('copy-prompt').click();assert($('status').textContent.includes('Ctrl+C'));assert($('status').classList.contains('error'));advance(7999);assert.equal($('status').hidden,false);advance(1);assert.equal($('status').hidden,true);
document.execCommand=()=>true;await $('copy-prompt').click();assert.equal($('status').textContent,'提示词已复制。');advance(2500);assert($('status').hidden);console.log('PASS denied clipboard honest manual fallback and confirmed execCommand success');
let resolveCopy;Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>new Promise(r=>resolveCopy=r)},configurable:true});const slowCopy=$('copy-prompt').click();await $('reset').click();const newerStatus=$('status').textContent;resolveCopy();await slowCopy;assert.equal($('status').textContent,newerStatus);console.log('PASS delayed copy completion cannot overwrite a newer state status');

await $('randomize').click();await $('save-local').click();const beforeOutput=JSON.parse(storage.get('visage.workbench.v0.1')),englishFull=prompt(),characterSeed=$('seed-value').textContent;
await $('prompt-language').click();assert.equal($('prompt-language').textContent,'中文');assert.match(prompt(),/[一-龥]/);assert.notEqual(prompt(),englishFull);assert.equal($('prompt-output').lang,'zh-CN');assert.equal($('seed-value').textContent,characterSeed);assert(!$('undo-randomize').disabled);
await $('save-local').click();const afterLanguage=JSON.parse(storage.get('visage.workbench.v0.1'));for(const key of ['profile','body','appearance','constraints','seed','sampling'])assert.deepEqual(afterLanguage[key],beforeOutput[key],key);
await $('prompt-language').click();assert.equal(prompt(),englishFull);console.log('PASS real bilingual prompt roundtrip preserves character, seed, locks, provenance and undo');
await event('hair-select','blunt_bob');await event('subject-appearance','SHOULD_NOT_LEAK_APPEARANCE');await event('subject-skin','SHOULD_NOT_LEAK_SKIN');await event('subject-shape','SHOULD_NOT_LEAK_FACE');
await event('output-scope','hair');assert.equal($('output-scope').value,'hair');const hairOnly=prompt();assert(hairOnly.length>0);assert(!/SHOULD_NOT_LEAK|Create a|realistic portrait|natural skin texture/i.test(hairOnly));
await event('output-scope','custom');assert.equal($('output-module-options').hidden,false);await toggle('output-module-face',true);assert(prompt().includes('SHOULD_NOT_LEAK_SKIN'));assert(!prompt().includes('SHOULD_NOT_LEAK_APPEARANCE'));await toggle('output-module-face',false);assert.equal(prompt(),hairOnly);await toggle('output-module-hair',false);assert.equal(prompt(),'');assert.equal($('output-summary').textContent,'未选模块');await toggle('output-module-hair',true);assert.equal(prompt(),hairOnly);console.log('PASS hair-only isolation, progressive custom combinations and explicit empty output');
await event('output-context','clay');assert.match(prompt(),/white|clay/i);assert(!/SHOULD_NOT_LEAK/.test(prompt()));await event('output-context','none');assert.equal(prompt(),hairOnly);
await event('output-context','random');const randomContext=prompt(),randomContextSeed=$('context-seed').textContent,randomCharacterSeed=$('seed-value').textContent;await $('tab-head').click();await $('tab-body').click();assert.equal(prompt(),randomContext);assert.equal($('context-seed').textContent,randomContextSeed);await $('save-local').click();const outputSaved=JSON.parse(storage.get('visage.workbench.v0.1'));await $('reset').click();await $('load-local').click();assert.equal(prompt(),randomContext);assert.deepEqual(JSON.parse(storage.get('visage.workbench.v0.1')).output,outputSaved.output);await $('reroll-context').click();assert.notEqual($('context-seed').textContent,randomContextSeed);assert.equal($('seed-value').textContent,randomCharacterSeed);console.log('PASS white-clay context isolation, frozen random context, persistence and separate context seed');
await event('output-scope','body');assert.equal($('body-enabled').checked,false);assert.equal($('capture').value,'head');assert(!/shoulder frame|pelvic frame/i.test(prompt()));await event('output-context','none');assert.equal(prompt(),'');console.log('PASS body-only does not enable body or change composition');

let resolveQuietCopy;Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>new Promise(r=>resolveQuietCopy=r)},configurable:true});const quietCopy=$('copy-prompt').click();await $('save-local').click();const saveStatus=$('status').textContent;resolveQuietCopy();await quietCopy;assert.equal($('status').textContent,saveStatus);
let rejectQuietCopy;Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>new Promise((resolve,reject)=>rejectQuietCopy=reject)},configurable:true});const deniedQuietCopy=$('copy-prompt').click();await $('select-prompt').click();const selectionStatus=$('status').textContent;selected=false;rejectQuietCopy(new Error('permission-denied'));await deniedQuietCopy;assert.equal($('status').textContent,selectionStatus);assert.equal(selected,false);console.log('PASS delayed clipboard success/failure cannot replace a newer non-mutating status or trigger fallback');
await $('reset').click();await $('save-local').click();const beforeUndoOutput=JSON.parse(storage.get('visage.workbench.v0.1'));await $('randomize').click();await $('prompt-language').click();await event('output-scope','face');await event('output-context','clay');await $('save-local').click();const currentOutputView=JSON.parse(storage.get('visage.workbench.v0.1')).output;await $('undo-randomize').click();await $('save-local').click();const afterUndoOutput=JSON.parse(storage.get('visage.workbench.v0.1'));assert.deepEqual(afterUndoOutput.output,currentOutputView);for(const key of ['profile','body','appearance','constraints','seed'])assert.deepEqual(afterUndoOutput[key],beforeUndoOutput[key],key);assert($('undo-randomize').disabled);console.log('PASS grouped reroll undo restores character while preserving later language/scope/context edits');
globalThis.Image=class{naturalWidth=500;naturalHeight=700;set src(value){queueMicrotask(()=>this.onload())}};const staticFile=new Blob(['harness-only-image'],{type:'image/png'});staticFile.name='static-reference.png';$('reference-file').files=[staticFile];await $('reference-file').dispatch('change');assert(!$('reference-label').textContent.includes('参数已更改'));await $('prompt-language').click();await event('output-scope','hair');await event('output-context','random');await $('reroll-context').click();assert(!$('reference-label').textContent.includes('参数已更改'));await event('head-face_geometry-face_length-number',65);assert($('reference-label').textContent.includes('参数已更改'));await $('clear-reference').click();console.log('PASS output-only edits do not falsely mark an imported static reference as changed');
